-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Feb 25, 2016 at 09:48 AM
-- Server version: 10.1.8-MariaDB
-- PHP Version: 5.6.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `database`
--

-- --------------------------------------------------------

--
-- Table structure for table `information`
--

CREATE TABLE `information` (
  `ID` int(11) NOT NULL,
  `debtors` varchar(9999) NOT NULL,
  `nature` varchar(9999) NOT NULL,
  `statement` varchar(9999) NOT NULL,
  `status` varchar(9999) NOT NULL,
  `Category` varchar(255) NOT NULL,
  `Keyword` varchar(255) NOT NULL,
  `DateModify` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `information`
--

INSERT INTO `information` (`ID`, `debtors`, `nature`, `statement`, `status`, `Category`, `Keyword`, `DateModify`) VALUES
(1, '<p>Norsheren Binti Ahmad.</p>', '<p>&bull; Summons and Statements of Claims dated 05/02/2010.</p>\r\n<p>&bull; Claim for the balance of the price of goods sold and delivered to the Defendant on a credit basis to the Defendant at the Defendant&rsquo;s request, full particulars of which have been supplied to th</p>', '<p>&bull; Defendant filed Defence and Counterclaim on 05/04/2010.</p>\r\n<p>&bull; Plaintiff filed a Reply and Defence to Counterclaim on 26/04/2010.</p>', '<p>&bull; Judgment entered on 18/3/2011 and Defendant to pay the plaintiff sum of RM93,991.08 being the costs of the Defendant&rsquo;s goods sold and delivered of the demised premises and interest at the rate of 1% per month on RM2780.30 from the 4th day of September.</p>', 'EDD', 'Debtors', '2016-01-17 21:36:02'),
(2, '<p>Summons No. 72-28-04-11</p>\r\n<p><strong>SEDC </strong></p>\r\n<p>vs.</p>\r\n<p><strong>Oya Aquaculture Sdn Bhd</strong></p>', '<p>&bull; Loss of rental from 28 April 2003 to 19 December 2003 @ RM 9,621.75</p>\r\n<p>&bull; Mesne profits at double rent from 19 December 2003 till delivery of possession. &bull; Possession of Lot 101, Block 28, Oya- Dalat Land District</p>\r\n<p>&bull; Interest @ 8% + costs.</p>\r\n<p>&bull; Filed on 5 February 2004.</p>', '<p>&bull; Defendant counter claim for RM282,319.00 as improvement to the land carried out by the Defendant out of the compensation @RM407,911.00 awarded by the Superintendent,Land &amp; Survey Department for acquisition of part of Lot 101, interest thereon @ 12% p.a. from 5 November 2003 and costs.</p>\r\n<p>&bull; Statement of Defence Filed on 21 June 2004.</p>', '<p>&bull; Trial :28/2/08, 19/3/08, 24/4/08.</p>\r\n<p>&bull; Judgment granted on 11/6/08 in favour of SEDC. Defendant to pay Plaintiff the sum RM14,191.20 with interest thereon at the rate of 8% per annum from 1/3/2004 till date of full and final settlement with costs to be taxed unless agreed and provided that costs for getting up do not exceed RM10,000.00 &nbsp;Court dismissed Defendant&rsquo;s counter claim.</p>\r\n<p>&bull; Defendant filed appeal on 17/9/2008.</p>\r\n<p>&bull; On 18/10/2011, COA dismissed the Appellant&rsquo;s appeal with cost of RM20,000.00</p>\r\n<p>&bull; CLOSED/SETTLED</p>', 'EDD', 'Debtors', '2016-01-17 21:35:46'),
(3, '<p>Suit No. 52-329-2008 (BTU)</p>\r\n<p><strong> SEDC </strong></p>\r\n<p>Vs.</p>\r\n<p><strong>Country Rim</strong></p>', '<p>&bull; Plaintiff&rsquo;s claim is for RM 143, 871.00 being the outstanding management fee for SEDC business premises in Serian, Bandung, Saratok and Block A, B &amp; C Miri.</p>\r\n<p>&bull; Interest on judgement sum @ 8% p.a. from the date of judgement until date of full and final settlement.</p>\r\n<p>&bull; Costs</p>\r\n<p>&bull; Summons filed on 1/12/2008</p>', '<p>&bull; NIL</p>', '<p>&bull; Judgment in Default of Appearance entered on 6/4/2009. Defendant to pay Plaintiff the sum RM143,871.90 with interest thereon at the rate of 8% per annum from the date of Judgment till date of full and final settlement and costs RM1,804.00.</p>\r\n<p>&bull; CCM during its 156th meeting held on 24 March 2010 agreed to consider the proposal to settle the judgment sum by paying in cash RM5,000.00 and installment of RM300.00 on or before the 7th day of subsequent month until full and final settlement.</p>\r\n<p>&bull; Judgment Debtor did not make regular payment.</p>\r\n<p>&bull; Recommend to execute the Judgment.</p>', 'EDD', 'Summons', '2016-01-17 21:35:09'),
(4, '<p>Suit No. 21-09-2009 (MR)/1</p>\r\n<p><strong>1) TK Pada Jutang </strong></p>\r\n<p><strong>2) TK Ngot Laing </strong></p>\r\n<p><strong>3) Jalong Wat</strong></p>\r\n<p><strong> 4) Nah Kujan </strong></p>\r\n<p><strong>5) Lah Unan </strong></p>\r\n<p>Vs.</p>\r\n<p><strong>1) Damai Cove Resorts Sdn. Bhd.</strong></p>\r\n<p><strong> 2) Samling Plywood (Lawas) Sdn. Bhd. </strong></p>\r\n<p><strong>3) Samling ReForestration (Bintulu) Sdn. Bhd. </strong></p>\r\n<p><strong>4) Director of Forests, Sarawak </strong></p>\r\n<p><strong>5) State Government of Sarawak</strong></p>', '<p>&bull; Plaintiff alleged that they have acquired and claimed native customary rights over the timber concession areas which have been licensed/ granted to Damai Cove Sdn. Bhd under various timber licenses issued by the Director of Forests and State Government. A Re-entry Hill Logging Timber Licence No. T/9089 had been issued to Damai Cove Sdn. Bhd. issued by the State Government through Director of Forests to harvest mechantable timber over the licence area.</p>\r\n<p>&bull; Summons dated 2/12/2009.</p>', '<p>&bull; NIL</p>', '<p>&bull; An application was filed by Damai Cove Resorts Sdn Bhd in 2010 for preliminary questions of law to be determined and/ or striking out the plaintiffs&rsquo; suit. The application was heard in April 2010 and dismissed. Following the High Court&rsquo;sdecision, an appeal was filed with the Court of Appeal. The appeal is still pending.</p>\r\n<p>&bull; In the meantime, the Director of Forests and the State Government have filed an application to strike out the plaintiffs&rsquo; claims on the ground that the claims are barred under the Public Authorities Protection Act 1948 and the Limitation Ordinance.</p>\r\n<p>&bull; Damai Cove Resorts Sdn Bhd has also filed another application to strike out the plaintiffs&rsquo; suit on the ground that the plaintiffs should have commenced the action by judicial review and not by writ. The two applications were heard in February 2012 and were allowed. The Court&rsquo;s decision was handed down on 30 April 2012.</p>\r\n<p>&bull; Plaintiff filed an appeal to Court of Appeal on 24/5/2012 against the High Court decision on 30/4/2012.</p>\r\n<p>&bull; Fixed for hearing by Court of Appeal on 10.02.2014.</p>\r\n<p>&bull; Fixed for case management on 15/5/2014 and the Registrar of the Court of Appeal directed that a further mention or hearing date will be fixed. Pending outcome of Federal Court decision on same point of law in another case.</p>', 'EDD', 'Damai Cove Sdn. Bhd', '2016-01-17 09:24:30'),
(5, '<p><span style="text-decoration: underline;">Suit No; 21-10-2009 (MR)/2</span></p>\r\n<p><strong> 1) TK Panai Irang</strong></p>\r\n<p><strong>2) TK Balan Jon </strong></p>\r\n<p><strong>3) Jeffrey Sibin</strong></p>\r\n<p><strong> 4) Perengky ka Liban</strong></p>\r\n<p><strong> 5) Gilang Vun Ungun</strong></p>\r\n<p>Vs.</p>\r\n<p><strong>1) Damai Cove Resorts Sdn. Bhd. </strong></p>\r\n<p><strong>2) Samling Plywood (Lawas) Sdn. Bhd.</strong></p>\r\n<p><strong> 3) Director of Forests, Sarawak </strong></p>\r\n<p><strong>4) State Government of Sarawak</strong></p>', '<p>&bull; Plaintiff alleged that they have acquired and claimed native customary rights over the timber concession areas which have been licensed/ granted to Damai Cove Sdn. Bhd under various timber licenses issued by the Director of Forests and State Government. A Re-entry Hill Logging Timber Licence No.T/9089 had been issued to Damai Cove Sdn. Bhd. Issued by the State Government through Director of Forests to harvest mechantable timber over the licence area.</p>\r\n<p>&bull; Summons dated 2/12/2009.</p>', '<p>&bull; NIL</p>', '<p>&bull; An application was filed by Damai Cove Resorts Sdn Bhd in 2010 for preliminary questions of law to be determined and/or striking out the plaintiffs&rsquo; suit. The application was heard in April 2011 and dismissed. Following the High Court&rsquo;s decision, an appeal was filed with the Court of Appeal. The appeal is still pending.</p>\r\n<p>&bull; In the meantime, the Director of Forests and the State Government have filed an application to strike out the plaintiffs&rsquo; claims on the ground that the claims are barred under the Public Authorities Protection Act 1948 and the Limitation Ordinance.</p>\r\n<p>&bull; Damai Cove Resorts Sdn Bhd has also filed another application to strike out the plaintiffs&rsquo; suit on the ground that the plaintiffs should have commenced the action by judicial review and not by writ. The two applications were heard in February 2012 and were allowed. The Court&rsquo;s decision was handed down on 30 April 2012.</p>\r\n<p>&bull; Plaintiff filed an appeal to Court of Appeal on 24/5/2012 against the High Court decision on 30/4/2012.</p>\r\n<p>&bull; Fixed for hearing by Court of Appeal on 10.02.2014.</p>\r\n<p>&bull; Fixed for case management on 15/5/2014 and the Registrar of the Court of Appeal directed that a further mention or hearing date will be fixed. Pending outcome of Federal Court decision on same point of law in another case.</p>', 'HRA', 'Hill Logging Timber Licence', '2016-01-27 08:14:17'),
(6, '<p><span style="text-decoration: underline;">Sessions Court Summons</span></p>\r\n<p>No: 52-512-2010-II</p>\r\n<p><strong>SEDC</strong></p>\r\n<p>Vs.</p>\r\n<p><strong>1) South-Pacific Maritime Sdn. Bhd.</strong></p>\r\n<p><strong>2) Tony Goh Sook San</strong></p>\r\n<p><strong>3) Lawrence Law Pee Hua</strong></p>', '<p>&bull; Summons and Statement of Claims filed on 08/04/2010.</p>\r\n<p>&bull; Plaintiff&rsquo;s claim is for RM117,357.73 with interest outstanding 18 months rental, unpaid electricity bills from October 2008 to February 2010, unpaid water bill from October 2008 to February 2010 of the Steamship Restaurant, situated at Kuching Waterfront.</p>\r\n<p>&bull; Judgment sum @ 8% p.a. from the date of judgment (31.10.2011) until date of full and final settlement</p>', '<p>&bull; Defendant filed Application to strike out SEDC claim under o. 14, r. 17 (b)(c) &amp; (d), Subordinate Court Rule, 1980 on the ground that SEDC is not the registered proprietor and/or has no possessory undivided right and title to KWF.</p>\r\n<p>&bull; SEDC has filed affidavits in reply on 25/10/2011 to oppose application as SEDC is a Statutory Body being entrusted by the State to maintain and manage Kuching Waterfront.</p>', '<p>&bull; Judgment was granted in favour of SEDC for the sum of RM117,357.73 with interest thereon at the rate of 8% per annum from 31.10.2011 until full and final settlement.</p>\r\n<p>&bull; South Pacific has filed an appeal to the High Court against the decision of the Sessions Court Judge and the same had been set down for mention on 25/9/2012 after a few adjournments.</p>\r\n<p>&bull; South Pacific being the appellant has withdrawn their Appeal in the Court of Appeal on 25/9/2012.</p>\r\n<p>&bull; Bankruptcy Notice had been filed against 2 Guarantors and proposed to pay 50% of the Judgment sum</p>\r\n<p>&bull; The management of Sara Urusharta only agrees to discount 20% of the Judgment sum.</p>\r\n<p>&bull; Payment made through 17 post dated cheques amounting to RM99,886.18.</p>\r\n<p>&bull; SUSB is monitoring the PD cheques.</p>', 'PTY', 'South-Pacific Maritime Sdn. Bhd.', '2016-01-17 08:41:17'),
(7, '<p><span style="text-decoration: underline;">Summons No: 52-201-2010-III </span></p>\r\n<p><strong>PPES Ternak Sdn. Bhd. </strong></p>\r\n<p>Vs.</p>\r\n<p><strong>Norsheren Binti Ahmad.</strong></p>', '<p>&bull; Summons and Statements of Claims dated 05/02/2010.</p>\r\n<p>&bull; Claim for the balance of the price of goods sold and delivered to the Defendant on a credit basis to the Defendant at the Defendant&rsquo;s request, full particulars of which have been supplied to the Defendant.</p>', '<p>&bull; Defendant filed Defence and Counterclaim on 05/04/2010. &bull; Plaintiff filed a Reply and Defence to Counterclaim on 26/04/2010.</p>', '<p>&bull; Judgment entered on 18/3/2011 and Defendant to pay the plaintiff sum of RM93,991.08 being the costs of the Defendant&rsquo;s goods sold and delivered of the demised premises and interest at the rate of 1% per month on RM2784.30 from the 4th day of September 2008 until the date of full and final settlement and interest at 8% per annum on RM91,206.78 from the date of Summons until the date of full and final settlementand court fees of RM240.00 Advocates fee of RM1,325.00 and the Defendant&rsquo;s counterclaim be dismissed with costs to be taxed to the Plaintiff.</p>\r\n<p>&bull; Personal Index Search revealed the Judgment Debtor has no assets in Kuching and Kota Samarahan.</p>\r\n<p>&bull; Execute the Judgment by Bankruptcy Proceedings</p>', 'AGRO', 'Bankcruptcy ', '2016-02-12 11:13:54'),
(8, '<p><span style="text-decoration: underline;">Sessions Court Summons No: SBW-53-33/12-2011</span></p>\r\n<p><strong> Muhammad Adam Aizat Bin Muhammad Izan</strong></p>\r\n<p>Vs.</p>\r\n<p><strong>1) Hamsiah Bt Ais </strong></p>\r\n<p><strong>2) SeDidik Sdn. Bhd.</strong></p>', '<p>&bull; Summons and Statement of Claims dated 28.12.2011 received from Plaintiff counsel on 11.1.2012. &bull; Plaintiff&rsquo;s claim is for the special damages in the sum RM1,798.15 as at 28.12.2011</p>\r\n<p>&bull; General Damages (to be assessed)</p>\r\n<p>&bull; Costs of Nursing Care of the plaintiff at RM1,00.00 per month and/or to be assessed</p>\r\n<p>&bull; Interest at the rate of 4% per annum from the date of judgment until the date of full and final settlement or Court deems just.</p>\r\n<p>&bull; Amount claimed/sued: RM1,798.15, Costs of Nursing Care of the plaintiff at RM1000.00 per month and/or to be assessed, interest rate of 4 % per annum, cost and other relief.</p>', '<p>&bull; Statement of Defence filed on 13.3.2012.</p>\r\n<p>&bull; Defendants denied the entire claim made by the Plaintiff as Defendant had taken pre-caution steps to avoid the incident.</p>', '<p>&bull; SeDidik offer for amicable settlement of RM5,000.00 plus cost as full and final settlement of the matter.</p>\r\n<p>&bull; Plaintiff has counter proposed Rm25,000.00 and special damages of RM1,798.15 plus 10 % cost as full and final settlement.</p>\r\n<p>&bull; Defendant counter proposed in the sum of RM20,000.00 as full and final settlement.</p>\r\n<p>&bull; Finally the matter has been settled amicably and the payment of RM20,000.00 has been made to Plaintiff being full and final settlement without any admission of liability.</p>\r\n<p>&bull; CLOSED/SETTLED</p>', 'EDD', 'CLOSED/SETTLE', '2016-01-17 08:31:17'),
(9, '<p>Summons No: KBR/31301/2013/0417</p>\r\n<p><strong>Jeffrey Bin Zaidi </strong></p>\r\n<p>Vs.</p>\r\n<p><strong>Sara Urusharta Sdn. Bhd</strong></p>', '<p>&bull; Encik Jeffrey Zaidi on 16 August 2011 was involved in a fight with a friend after office hours at Masjid Bahagian Kuching area as he was accused of causing grievous injury by his victim. Subsequently he was arrested by the police and was remanded under Section 324 of Penal Code. He was charged and convicted for causing grievous hurt and sentenced to 2 years imprisonment. His appeal to High Court was dismissed. His appeal against conviction was dismissed by the Court of Appeal but the Court Allowed his appeal against sentence by reducing his with imprisonment to 28 days with effect from 7 February 2013 and fine of RM5,000.00.</p>\r\n<p>&bull; On 25/7/2013, disciplinary committee was formed.</p>\r\n<p>&bull; On 18/10/2013, Disciplinary Committee decided to dismiss Jeffrey Zaidi pursuant to Regulation 28(3) of the Statutory Bodies Disciplinary Regulations. His appeal to Disciplinary Action Committee was dismissed.</p>\r\n<p>&bull; Encik Jeffrey Zaidi complained to Labour office in Kuching pursuant to his termination on 14/10/2103 by SUSB,claiming:</p>\r\n<p>&bull; -Gaji Ganti Notis amounting RM3,223.10; and</p>\r\n<p>&bull; - Termination Benefits RM17,047.80.</p>', '<p>&bull; Encik Jeffrey denied that the fight was happened outside office hours and it is only considered as incident.</p>\r\n<p>&bull; Futher, hee sends the appeal letter to SUSB on 21/10/2013 informed that he was not satisfied with the Disciplinary Committee decision against him.</p>\r\n<p>&bull; Among other his appeal was: a) SUSB should give him three (3) months&rsquo; notice of termination; b) SUSB should give him compensation as per agreed to him by verbally; and c) SUSB to continue paying his salary until December 2013.</p>', '<p>&bull; Complainant&rsquo;s claim was fixed for mentioned on 11/12/2013 at Mahkamah Buruh, Kuching.</p>\r\n<p>&bull; The matter was fixed on 21/1/2014 for trial at Mahkamah Buruh Kuching.</p>\r\n<p>&bull; The case has been further fixed for hearing/trial on 13/2/2014 at Mahkamah Buruh, Kuching. &bull; On 13/2/2014, Labour Court delivered its ruling that the complainant&rsquo;s claim to challenge his dismissal/termination is procedurally flawed. His claim should proceeded by way of Judicial Review instead of filing his claim in the Labour court. As such, the complainant&rsquo;s claim ought to be dismissed. &bull; The case was tried on 19/3/2014 at Mahkamah Buruh, Kuching.</p>\r\n<p>&bull; On 30/4/2014, the Labour Court dismissed the employee&rsquo; claims.</p>\r\n<p>&bull; To date no appeal filed by Pengadu.</p>', 'General', 'Sara Urusharta Sdn. Bhd', '2016-01-17 08:21:00'),
(10, '<p>Summons No. KCH-A52-138/6-2013</p>\r\n<p><strong>Sara Urusharta Sdn.Bhd. </strong></p>\r\n<p>Vs.</p>\r\n<p><strong>Soh Huang Siah</strong></p>', '<p>&bull; SUSB commenced legal action against the Defendant for the outstanding amount owing for the Steamship Building as follows: - For a sum of RM299,463.75 being the amount owed for the:-</p>\r\n<p>&bull; a) License fee from February 2009 to August 2012 &ndash; RM223,600.00</p>\r\n<p>&bull; b) Electricity charges from 1.04.08 &ndash; 1.08.12 &ndash; RM154,535.49</p>\r\n<p>&bull; c) Water charges from 1.03.2008 &ndash; 1.08.2012 &ndash; RM1,028.26</p>\r\n<p>&bull; Defendant&rsquo;s claim that:</p>\r\n<p>&bull; A declaration that the license agreement is null and void and of no effect</p>\r\n<p>&bull; Repayment of the renovation costs amounting RM240,000.00</p>\r\n<p>&bull; Refund all monies had or received from the Defendant purportedly received under and in connection with the License Agreement.</p>', '<p>&bull; NIL</p>', '<p>&bull; The case has been set down for mediation in the Sessions Court at Kuching on 25/11/2013 at 9.00am.</p>\r\n<p>&bull; Fixed for trial on 24, 25 and 27 February 2014.</p>\r\n<p>&bull; Testify and produce the documents on 10,21,26 and 28 March 2014.</p>\r\n<p>&bull; On 18/7/2014, the trial Judge ruled that</p>\r\n<p>&bull; The License Agreement between the Plaintiff Sara Urusharta Sdn. Bhd. And the Defendant Soh Huang Siah is null and void and of no legal effect.</p>\r\n<p>&bull; The plaintiff&rsquo;s claim is therefore dismissed.</p>\r\n<p>&bull; The Defendant&rsquo;s counterclaim for renovation costs of RM240,000.00 is allowed</p>\r\n<p>&bull; Plaintiff to pay Defendant&rsquo;s costs RM27,000.00</p>\r\n<p>&bull; In meantime, SUSB has filed a Notice of Appeal.</p>', 'PTY', 'SUSB', '2016-01-17 08:31:35'),
(14, '<p>Sessions Court Suit No. KCH-B52-3/3-2014</p>\r\n<p><strong>Robin Goh Boon Thye @ Robin Anak Santok </strong></p>\r\n<p>&amp;</p>\r\n<p><strong>3 Others </strong></p>\r\n<p>Vs.</p>\r\n<p><strong>Sara Urusharta Sdn. Bhd</strong></p>', '<p>&bull; Robin Goh &amp; three others have on 6 March 2014 filed a suit against Sara Urusharta Sdn Bhd for breach of contract in respect of the tenancy for Top Lounge , and claiming the following: - Purchase price of the business and renovation cost in the sum of RM315,855.30;</p>\r\n<p>&bull; Compensation to the Plaintiffs&rsquo; staff in the sum of RM9,200.00;</p>\r\n<p>&bull; Loss of profits from terminated events in the sum of RM37,959.00;</p>\r\n<p>&bull; Loss of profits from business in the sum of RM109,200.00;</p>\r\n<p>&bull; Interest on the above sums as at the rate of 5% per annum from the date of this Writ until the date of Judgement;</p>\r\n<p>&bull; Interest on the above sums at the rate of 5% per annum from the date of judgement until full and final payment;</p>\r\n<p>&bull; Cost;</p>\r\n<p>&bull; Such further and other relief as the Court deems fit and just.</p>', '<p>&bull; Defence filed on 3/4/2014</p>\r\n<p>&bull; Sara Urusharta Sdn Bhd will be relying on the defence of frustration of contract &ndash; that the termination of the plaintiffs&rsquo; tenancy was occasioned by a decision/directive of the Federal and State Government to convert and utilise Levels 4 &amp; 5 of Taman Kereta as a UTC.</p>', '<p>&bull; Plaintiffs&rsquo; solicitor has filed a Notice to Attend Pre-Trial Case management (PTCM) which was fixed on 10 June 2014.</p>\r\n<p>&bull; During the PTCM, Court directed that a) Plaintiff to file Bundle of Pleadings and Bundle of Documents by 30/9/2014 b) Defendents to file Bundle of Documents by 30/9/2014. c) Plaintiff will call 4 witnesses and require 2 days for trial. Defendant will also be calling 4 witnesses and requires 2 days for trial. Trial fixed on 25-27/2/2015 and on 10/3/2015. d) The case will be further mentioned on 6/11/2014.</p>', 'AGRO', 'Taman Kereta', '2016-01-17 08:31:43'),
(15, '<p>Sessions Court Suit No. KCH-B52-3/3-2014</p>\r\n<p><strong>Robin Goh Boon Thye @ Robin Anak Santok &amp; 3 Others</strong></p>\r\n<p>Vs.</p>\r\n<p><strong>Sara Urusharta Sdn. Bhd</strong></p>', '<p>&bull; Robin Goh &amp; three others have on 6 March 2014 filed a suit against Sara Urusharta Sdn Bhd for breach of contract in respect of the tenancy for Top Lounge , and claiming the following: - Purchase price of the business and renovation cost in the sum of RM315,855.30;</p>\r\n<p>&bull; Compensation to the Plaintiffs&rsquo; staff in the sum of RM9,200.00;</p>\r\n<p>&bull; Loss of profits from terminated events in the sum of RM37,959.00;</p>\r\n<p>&bull; Loss of profits from business in the sum of RM109,200.00;</p>\r\n<p>&bull; Interest on the above sums as at the rate of 5% per annum from the date of this Writ until the date of Judgement;</p>\r\n<p>&bull; Interest on the above sums at the rate of 5% per annum from the date of judgement until full and final payment;</p>\r\n<p>&bull; Cost;</p>\r\n<p>&bull; Such further and other relief as the Court deems fit and just.</p>', '<p>&bull; Defence filed on 3/4/2014</p>\r\n<p>&bull; Sara Urusharta Sdn Bhd will be relying on the defence of frustration of contract &ndash; that the termination of the plaintiffs&rsquo; tenancy was occasioned by a decision/directive of the Federal and State Government to convert and utilise Levels 4 &amp; 5 of Taman Kereta as a UTC.</p>', '<p>&bull; Plaintiffs&rsquo; solicitor has filed a Notice to Attend Pre-Trial Case management (PTCM) which was fixed on 10 June 2014.</p>\r\n<p>&bull; During the PTCM, Court directed that</p>\r\n<p>a) Plaintiff to file Bundle of Pleadings and Bundle of Documents by 30/9/2014</p>\r\n<p>b) Defendents to file Bundle of Documents by 30/9/2014.</p>\r\n<p>c) Plaintiff will call 4 witnesses and require 2 days for trial. Defendant will also be calling 4 witnesses and requires 2 days for trial. Trial fixed on 25-27/2/2015 and on 10/3/2015.</p>\r\n<p>d) The case will be further mentioned on 6/11/2014.</p>', 'EDD', 'Summons', '2016-01-17 21:37:40'),
(20, '<p>Summons No: KBR/31301/2013/0417</p>\r\n<p><strong>Jeffrey Bin Zaidi </strong></p>\r\n<p>Vs.</p>\r\n<p><strong>Sara Urusharta Sdn. Bhd</strong></p>', '<p>Encik Jeffrey Zaidi on 16 August 2011 was involved in a fight with a friend after office hours at Masjid Bahagian Kuching area as he was accused of causing grievous injury by his victim. Subsequently he was arrested by the police and was remanded under Section 324 of Penal Code. He was charged and convicted for causing grievous hurt and sentenced to 2 years imprisonment. His appeal to High Court was dismissed. His appeal against conviction was dismissed by the Court of Appeal but the Court Allowed his appeal against sentence by reducing his with imprisonment to 28 days with effect from 7 February 2013 and fine of RM5,000.00.</p>\r\n<p>&bull; On 25/7/2013, disciplinary committee was formed.</p>\r\n<p>&bull; On 18/10/2013, Disciplinary Committee decided to dismiss Jeffrey Zaidi pursuant to Regulation 28(3) of the Statutory Bodies Disciplinary Regulations. His appeal to Disciplinary Action Committee was dismissed.</p>\r\n<p>&bull; Encik Jeffrey Zaidi complained to Labour office in Kuching pursuant to his termination on 14/10/2103 by SUSB,claiming:</p>\r\n<p>&bull; Gaji Ganti Notis amounting RM3,223.10; and</p>\r\n<p>&bull; Termination Benefits RM17,047.80.</p>', '<p>&bull; Encik Jeffrey denied that the fight was happened outside office hours and it is only considered as incident.</p>\r\n<p>&bull; Futher, he sends the appeal letter to SUSB on 21/10/2013 informed that he was not satisfied with the Disciplinary Committee decision against him.</p>\r\n<p>&bull; Among other his appeal was:</p>\r\n<p>a) SUSB should give him three (3) months&rsquo; notice of termination;</p>\r\n<p>b) SUSB should give him compensation as per agreed to him by verbally; and</p>\r\n<p>c) SUSB to continue paying his salary until December 2013.</p>', '<ul>\r\n<li>Case Pending</li>\r\n</ul>', 'General', 'maps', '2016-01-27 15:06:17');

-- --------------------------------------------------------

--
-- Table structure for table `userinfo`
--

CREATE TABLE `userinfo` (
  `ID` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `FirstName` text NOT NULL,
  `LastName` text NOT NULL,
  `email` text NOT NULL,
  `AccessLevel` int(11) NOT NULL,
  `Division` varchar(255) NOT NULL,
  `DateRegister` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `userinfo`
--

INSERT INTO `userinfo` (`ID`, `username`, `password`, `FirstName`, `LastName`, `email`, `AccessLevel`, `Division`, `DateRegister`) VALUES
(1, 'admin', 'sedc@1234', 'ahmad', 'feroz', 'ifanunik@yahoo.com', 1, 'PTY', '2015-12-14 08:00:00'),
(2, 'Nawab', 'sedc@1234', 'Ahmad', 'Nawab', 'Nawab@sedc.com', 2, 'EDD', '2016-01-10 15:49:51'),
(3, 'menten', 'sedc@1234', 'Abang', 'Menten', 'James@pibulundu.my', 3, 'ICT', '2016-01-10 15:50:46'),
(4, 'feroz', 'sedc@1234', 'ahmad', 'feroz', 'feroz@sedc.my', 2, 'LAD', '2016-01-10 21:26:26'),
(5, 'Redha', 'sedc@1234', 'Ali Redha', 'Sapuan', 'Redha@sedc.my', 2, 'EDD', '2016-01-17 17:11:09');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `information`
--
ALTER TABLE `information`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `userinfo`
--
ALTER TABLE `userinfo`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `information`
--
ALTER TABLE `information`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
--
-- AUTO_INCREMENT for table `userinfo`
--
ALTER TABLE `userinfo`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
